export const ROLES = Object.freeze({
  ADMIN: 1,
  STAFF: 2,
  CHAUFFEUR: 3,
  AGENCY_AGENT: 4,
  CLIENT: 5,
});

export const ROLE_NAMES = Object.freeze({
  1: 'ADMIN',
  2: 'STAFF',
  3: 'CHAUFFEUR',
  4: 'AGENCY_AGENT',
  5: 'CLIENT',
});

export const LEGACY_RESERVATION_STATUS = Object.freeze({
  PENDING: 0,
  CONFIRMED: 1,
  COMPLETED: 2,
  CANCELLED: 3,
});

export const SERVICE_CODES = Object.freeze([
  'CHAUFFEUR',
  'TRANSFER',
  'CAR_RENTAL',
  'AIRPORT_VIP',
  'CONCIERGE',
]);

export const ASSIGNMENT_TRANSITIONS = Object.freeze({
  OFFERED: ['ACKNOWLEDGED', 'DECLINED', 'CANCELLED'],
  ACKNOWLEDGED: ['PREPARING', 'CANCELLED'],
  PREPARING: ['ON_THE_WAY', 'CANCELLED'],
  ON_THE_WAY: ['ARRIVED', 'CANCELLED'],
  ARRIVED: ['WAITING', 'PASSENGER_ONBOARD', 'NO_SHOW', 'CANCELLED'],
  WAITING: ['PASSENGER_ONBOARD', 'NO_SHOW', 'CANCELLED'],
  PASSENGER_ONBOARD: ['IN_SERVICE'],
  IN_SERVICE: ['AT_STOP', 'DROPOFF_REACHED'],
  AT_STOP: ['IN_SERVICE', 'DROPOFF_REACHED'],
  DROPOFF_REACHED: ['COMPLETED'],
  NO_SHOW: [],
  COMPLETED: [],
  DECLINED: [],
  CANCELLED: [],
});

export const TERMINAL_ASSIGNMENT_STATUSES = Object.freeze([
  'NO_SHOW',
  'COMPLETED',
  'DECLINED',
  'CANCELLED',
]);
