import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import path from 'node:path';
import { env, corsOrigins } from './config/env.js';
import { logger } from './common/logger.js';
import { errorHandler, notFoundHandler } from './common/errors.js';
import { authRouter } from './modules/auth.js';
import { clientRouter } from './modules/client.js';
import { catalogRouter } from './modules/catalog.js';
import { bookingRouter } from './modules/bookings.js';
import { paymentRouter } from './modules/payments.js';
import { chauffeurRouter } from './modules/chauffeur.js';
import { agentRouter } from './modules/agent.js';
import { chatRouter } from './modules/chat.js';
import { notificationRouter } from './modules/notifications.js';
import { backofficeRouter } from './modules/backoffice.js';
import { openapi } from './openapi.js';
export const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
morgan.token('request-id', (req) => String(req.headers['x-request-id'] ?? '-'));
app.use(morgan(':method :url :status :response-time ms reqId=:request-id', {
    stream: { write: (message) => logger.http(message.trim()) }
}));
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: (origin, cb) => !origin || corsOrigins.includes(origin) ? cb(null, true) : cb(new Error('CORS blocked')), credentials: true }));
app.use(compression());
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(rateLimit({ windowMs: 60_000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use(`/${env.UPLOAD_DIR.replace(/^\/+/, '')}`, express.static(path.resolve(process.cwd(), env.UPLOAD_DIR)));
app.get('/health', (_req, res) => res.json({ success: true, service: 'drive-luxury-backend', time: new Date().toISOString() }));
app.use('/docs', swaggerUi.serve, swaggerUi.setup(openapi));
const api = express.Router();
api.use('/auth', authRouter);
api.use('/client', clientRouter);
api.use('/catalog', catalogRouter);
api.use('/bookings', bookingRouter);
api.use('/payments', paymentRouter);
api.use('/chauffeur', chauffeurRouter);
api.use('/agent', agentRouter);
api.use('/chat', chatRouter);
api.use('/notifications', notificationRouter);
api.use('/backoffice', backofficeRouter);
app.use(env.API_PREFIX, api);
app.use(notFoundHandler);
app.use(errorHandler);
