const endpoint = (summary, tags) => ({ summary, tags, responses: { '200': { description: 'Success' }, '400': { description: 'Bad request' }, '401': { description: 'Unauthorized' }, '403': { description: 'Forbidden' } } });
export const openapi = {
    openapi: '3.0.3',
    info: { title: 'Drive Luxury Mobile API', version: '1.0.0', description: 'Integration API for Client, Chauffeur and Rental Agent apps using the existing Drive Luxury database.' },
    servers: [{ url: '/api/v1' }],
    components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } },
    security: [{ bearerAuth: [] }],
    paths: {
        '/auth/client/register': { post: { ...endpoint('Self-register Client/Customer account', ['Auth']), security: [] } },
        '/auth/chauffeur/register': { post: { ...endpoint('Self-register Chauffeur/Driver account', ['Auth']), security: [] } },
        '/auth/driver/register': { post: { ...endpoint('Self-register Driver account (alias)', ['Auth']), security: [] } },
        '/auth/agent/register': { post: { ...endpoint('Self-register Rental Agent account', ['Auth']), security: [] } },
        '/auth/register': { post: { ...endpoint('Register customer (backward-compatible alias)', ['Auth']), security: [] } },
        '/auth/login': { post: { ...endpoint('Email/password login', ['Auth']), security: [] } },
        '/auth/google': { post: { ...endpoint('Google customer login', ['Auth']), security: [] } },
        '/auth/refresh': { post: { ...endpoint('Rotate refresh token', ['Auth']), security: [] } },
        '/auth/logout': { post: { ...endpoint('Logout / revoke token', ['Auth']), security: [] } },
        '/auth/me': { get: endpoint('Current authenticated user', ['Auth']) },
        '/auth/password/forgot': { post: { ...endpoint('Request password reset', ['Auth']), security: [] } },
        '/auth/password/reset': { post: { ...endpoint('Reset password with token', ['Auth']), security: [] } },
        '/client/dashboard': { get: endpoint('Client dashboard', ['Client']) },
        '/client/profile': { get: endpoint('Client profile', ['Client']), patch: endpoint('Update client profile', ['Client']) },
        '/client/bookings/{id}/tracking': { get: endpoint('Client live tracking snapshot', ['Client']) },
        '/catalog/services': { get: endpoint('Service catalog and legacy service mapping', ['Catalog']) },
        '/catalog/vehicles/available': { get: endpoint('Available vehicles', ['Catalog']) },
        '/catalog/options': { get: endpoint('Available add-ons', ['Catalog']) },
        '/catalog/quotes': { post: endpoint('Calculate authoritative server quote', ['Catalog']) },
        '/bookings/drafts': { post: endpoint('Create booking draft - Step 1', ['Bookings']) },
        '/bookings/drafts/{id}/details': { patch: endpoint('Set booking details - Step 2', ['Bookings']) },
        '/bookings/drafts/{id}/options': { patch: endpoint('Set vehicle/options - Step 3', ['Bookings']) },
        '/bookings/drafts/{id}/quote': { post: endpoint('Generate quote', ['Bookings']) },
        '/bookings/drafts/{id}/checkout': { post: endpoint('Checkout / create reservation and payment - Step 4', ['Bookings']) },
        '/bookings': { get: endpoint('List client bookings', ['Bookings']) },
        '/bookings/{id}': { get: endpoint('Booking detail', ['Bookings']), patch: endpoint('Modify eligible booking fields', ['Bookings']) },
        '/bookings/{id}/cancel': { post: endpoint('Cancel booking', ['Bookings']) },
        '/bookings/{id}/receipt': { get: endpoint('Receipt/invoice view', ['Bookings']) },
        '/payments/reservations/{reservationId}/create': { post: endpoint('Create/retry payment provider session', ['Payments']) },
        '/payments/{id}/confirm': { post: endpoint('Confirm payment', ['Payments']) },
        '/payments/{id}': { get: endpoint('Payment status', ['Payments']) },
        '/chauffeur/dashboard': { get: endpoint('Driver dashboard', ['Chauffeur']) },
        '/chauffeur/rides': { get: endpoint('Assigned rides', ['Chauffeur']) },
        '/chauffeur/rides/{id}': { get: endpoint('Assigned ride detail', ['Chauffeur']) },
        '/chauffeur/rides/{id}/start': { post: endpoint('Start chauffeur service', ['Chauffeur']) },
        '/chauffeur/rides/{id}/checkpoints': { post: endpoint('Advance ride checkpoint', ['Chauffeur']) },
        '/chauffeur/rides/{id}/location': { post: endpoint('Publish live GPS location', ['Chauffeur']) },
        '/chauffeur/rides/{id}/expenses': { post: endpoint('Submit chauffeur expense', ['Chauffeur']) },
        '/agent/contracts': { get: endpoint('Assigned rental contracts', ['Rental Agent']) },
        '/agent/contracts/{id}': { get: endpoint('Rental contract detail', ['Rental Agent']) },
        '/agent/contracts/{id}/inspections': { post: endpoint('Start pickup/return inspection', ['Rental Agent']) },
        '/agent/inspections/{id}/readings': { patch: endpoint('Set mileage/fuel', ['Rental Agent']) },
        '/agent/inspections/{id}/media': { post: endpoint('Upload required inspection media', ['Rental Agent']) },
        '/agent/inspections/{id}/checklist': { put: endpoint('Complete guided checklist', ['Rental Agent']) },
        '/agent/inspections/{id}/damages': { post: endpoint('Record damage and evidence', ['Rental Agent']) },
        '/agent/inspections/{id}/signature': { put: endpoint('Capture client signature', ['Rental Agent']) },
        '/agent/inspections/{id}/complete': { post: endpoint('Complete delivery/return inspection', ['Rental Agent']) },
        '/chat/reservations/{id}/conversation': { post: endpoint('Open reservation conversation', ['Communication']) },
        '/chat/conversations/{id}/messages': { get: endpoint('Read messages', ['Communication']), post: endpoint('Send message', ['Communication']) },
        '/chat/reservations/{id}/masked-call': { post: endpoint('Create masked calling session', ['Communication']) },
        '/notifications/devices': { post: endpoint('Register push device', ['Notifications']) },
        '/notifications': { get: endpoint('List notifications', ['Notifications']) },
        '/backoffice/bookings/{id}/decision': { post: endpoint('Confirm/reject booking for test/back-office integration', ['Back-office']) },
        '/backoffice/bookings/{id}/assign-chauffeur': { post: endpoint('Assign chauffeur', ['Back-office']) },
        '/backoffice/bookings/{id}/assign-agent': { post: endpoint('Assign rental agent', ['Back-office']) }
    }
};
